name: Build with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'maven'
    - name: build jar
      run: mvn -B package --file pom.xml
    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '17.0.7'
        distribution: 'graalvm'
    - name: build native image
      run: mvn -B package -P native-image --file pom.xml
